apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: patch-example
resources:
- deployment/backend1.yaml
- deployment/web1.yaml
- deployment/web2.yaml

patches:
- target:
    kind: Deployment
    name: web.*
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: this_value_is_ignored
    spec:
      replicas: 10

