apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-1
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: example
          image: docker.io/alpine:latest
          command:
            - sleep
            - inf
