apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-2
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: example
          image: docker.io/alpine:latest
          command:
            - sleep
            - inf
